### ISSUE TITLE
can not initiate instance of new org.nativescript.widgets.Async.CompleteCallback()

### ISSUE THREAD

**Issue by shuyih** [NativeScript/tns-core-modules-widgets#49]
files in my app:

**.ts**
import \* as httpModule from 'http';
....
private getActivityViaHttp()<T> : Promise<any> {
        **return httpModule.getJSON('http://httpbin.org/ip');**
}

**result**
httpModule.getJSON('http://httpbin.org/ip') returns '**undefined**'

**debug output** 
following function failed to execute:

`completeCallback = new org.nativescript.widgets.Async.CompleteCallback({
        onComplete: function (result, context) {
            onRequestComplete(context, result);
        }
    });`

**onComplete is never called/executed:**
`onComplete: function (result, context) {
            onRequestComplete(context, result);`

which, I believe, causes the http call never sent to the server as Fiddler indicated. 

Any thoughts on why `new org.nativesript.widgets.Async.CompleteCalback() /  onRequestComplete(context, result);` not executed?

**Comment by NickIliev** [comment]
Hey @shuyih 

I have tested your example and it works as expected on my side - the only differences that I made in your code is that I am returning **Promise<any>** as the promise should have type argument. [Here is the sample app](https://github.com/NickIliev/NativeScript-issues/tree/master/others/httpPromise) where I am testing this case. Basically the code is the following:

main-view-model.ts

```
import {Observable} from 'data/observable';
import * as httpModule from 'http';

export class MyViewModel extends Observable {

  constructor() {
    super();
  }

  public onTap() {
    this.getActivityViaHttp().then(res => {
      console.log("IP: " + res.origin);
    })
  }

  private getActivityViaHttp() : Promise<any> {
    return httpModule.getJSON('http://httpbin.org/ip');
  }
}
```

main-page.ts

```
import { MyViewModel } from './main-view-model';

export function navigatingTo(args: EventData) {
  let page = <Page>args.object;
  page.bindingContext = new MyViewModel();
}
```

main-page.xml

```
<Button text="TAP" tap="{{ onTap }}" />
```
